name: Check Copyright Header

on: [push, pull_request]

jobs:
  copyright-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read Header
        id: read_header
        run: |
          HEADER_CONTENT=$(cat etc/header.txt)
          echo "::set-output name=header::$HEADER_CONTENT"

      - name: Check Files for Header
        run: |
          # Retrieve the header content from previous step
          HEADER="${{ steps.read_header.outputs.header }}"
          
          # Find Java files without the header and list them
          MISSING_HEADER=""
          for file in $(find src -name "*.java"); do
            if ! awk 'NR==1,NR==10' "$file" | grep -F -q "$HEADER"; then
              MISSING_HEADER+="$file\n"
            fi
          done

          # Fail if any file is missing the correct header
          if [ -n "$MISSING_HEADER" ]; then
            echo -e "The following files are missing the required copyright header:\n$MISSING_HEADER"
            exit 1
          else
            echo "All files have the correct copyright header."
          fi
