name: Check Copyright Header

on: [push, pull_request]

jobs:
  copyright-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read Copyright Header
        id: read_header
        run: |
          # Read the header from the file
          HEADER_CONTENT=$(cat etc/header.txt)
          echo "::set-output name=header::$HEADER_CONTENT"

      - name: Run Copyright Check
        run: |
          # Retrieve the header content from the previous step
          HEADER="${{ steps.read_header.outputs.header }}"
          
          # Find all Java files and check for the header
          MISSING_HEADER=$(find src -name "*.java" ! -exec grep -q "$HEADER" {} \; -print)
          
          # Fail if any file is missing the correct header
          if [ -n "$MISSING_HEADER" ]; then
            echo "The following files are missing the required copyright header:"
            echo "$MISSING_HEADER"
            exit 1
          else
            echo "All files have the correct copyright header."
          fi
