name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: self-hosted
    if: github.event_name == 'push' && contains(github.event.head_commit.message, '[deploy]') == true


    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '21'

    - name: Build with Maven
      run: mvn clean package

    - name: Build Docker image
      run: docker build -t ci-cd:latest .

    - name: Save Docker image to file
      run: docker save ci-cd:latest -o ci-cd-latest.tar

    - name: Copy Docker image to server
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "ci-cd-latest.tar"
        target: "~/"

    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sudo docker load -i ~/ci-cd-latest.tar
          sudo docker stop ci-cd-container || true
          sudo docker rm ci-cd-container || true
          sudo docker run -d --name ci-cd-container -p 80:80 ci-cd:latest